(define "items_light_ger"

;// pistol

;// smg
	{item "mp40"					"ammo" 999 {value 1}}

;// mg
	{item "mgun_ger" "belt" "ap"	"ammo" 999 {value 1}}
	{item "mgun_ger" "belt" "ap2"	"ammo" 999 {value 1}}
	{item "mgun_ger" "belt"			"ammo" 999 {value 1}}
	{item "mgun_ger" "mg13"			"ammo" 999 {value 1}}
	{item "mgun_ger" "drum"			"ammo" 999 {value 1}}
	{item "mgun_ger" "doubledrum"	"ammo" 999 {value 1}}
	{item "mgun_ger" "doubledrum" "ap" "ammo" 999 {value 1}}
	{item "mgun_ger" "doubledrum" "ap2" "ammo" 999 {value 1}}
	{item "zb26_mag"					"ammo" 999 {value 1}}

;// rifle
	{item "atrifle_ger"				"ammo" 999  {value 1}}
	{item "rifle_ger" "clip"		"ammo" 999 {value 1}}
	{item "rifle_ger" "gewehr"		"ammo" 999 {value 1}}
	{item "stg44"					"ammo" 999 {value 1}}
	{item "fg42"					"ammo" 999 {value 1}}

;// AT
	{item "k98_antitank"			"ammo" 999  {value 1}}
	{item "k98_grenade"	"he"		"ammo" 999  {value 1}}
	{item "k98_grenade"	"heat"		"ammo" 999  {value 1}}
	{item "k98_grenade"	"heata"		"ammo" 999  {value 1}}
	{item "panzershreck"			"ammo" 999  {value 1}}

;// Light weaponry
	{item "mortarger_80" "he"		"ammo" 999  {value 1}}
	{item "mortarger_80" "sm"		"ammo" 999  {value 1}}
	{item "mortarger_100" "he"		"ammo" 999  {value 1}}
	{item "mortarger_100" "sm"		"ammo" 999  {value 1}}
	{item "mortarger_120" "he"		"ammo" 999  {value 1}}

;// Grenade
	{item "grenade" "m24"					999  {value 1}}
	{item "grenade" "m24_splinter"			999  {value 1}}

	{item "grenade" "m24_geballteladung"	999  {value 1}}
	{item "grenade" "hafthohlladung"		999  {value 1}}
	{item "grenade" "pwm_l"					999  {value 1}}
	{item "grenade" "molotov_cocktail"		999  {value 1}}

	{item "grenade" "m24_smoke"				999  {value 1}}
	{item "grenade" "nbk39"					999  {value 1}}
	{item "grenade" "nbks"					999  {value 1}}
)

(define "items_light_rus"

;// pistol
	{item "tt33"					"ammo" 999 {value 1}}
	{item "revolver_clip"			"ammo" 999 {value 1}}

;// smg
	{item "ppd_drum"				"ammo" 999 {value 1}}
	{item "pps_stick"				"ammo" 999 {value 1}}
	{item "ppsh_drum"				"ammo" 999 {value 1}}
	{item "ppsh_stick"				"ammo" 999 {value 1}}

;// mg
	{item "hmgun_rus" "ap"			"ammo" 999 {value 1}}
	{item "hmgun_rus" "api"			"ammo" 999 {value 1}}
	{item "mgun_rus" "dp"			"ammo" 999 {value 1}}
	{item "mgun_rus" "dt"			"ammo" 999 {value 1}}
	{item "mgun_rus" "belt"			"ammo" 999 {value 1}}
	{item "mgun_rus" "belt" "ap"	"ammo" 999 {value 1}}
	{item "mgun_rus" "belt"	"api"	"ammo" 999 {value 1}}

;// rifle
	{item "atrifle_rus"				"ammo" 999  {value 1}}
	{item "rifle_rus" "clip"		"ammo" 999 {value 1}}
	{item "rifle_rus" "svt"			"ammo" 999 {value 1}}
	{item "shotgun"					"ammo" 999 {value 1}}

;// AT
	{item "dyakonov"				"ammo" 999  {value 1}}
	{item "vpgs41"					"ammo" 999  {value 1}}

;// Light weaponry
	{item "mortarrus_50" "he"		"ammo" 999  {value 1}}
	{item "mortarrus_82" "he"		"ammo" 999  {value 1}}
	{item "mortarrus_82" "sm"		"ammo" 999  {value 1}} ;// is actually "ic"
	{item "mortarrus_120" "he"		"ammo" 999  {value 1}}
	{item "mortarrus_120" "sm"		"ammo" 999  {value 1}}
	{item "mortarrus_120" "ic"		"ammo" 999  {value 1}}

;// Grenade
	{item "grenade" "f1" 					999  {value 1}}
	{item "grenade" "rgd33" 				999  {value 1}}

	{item "grenade" "rpg40"					999  {value 1}}
	{item "grenade" "rpg43"					999  {value 1}}
	{item "grenade" "molotov_cocktail"		999  {value 1}}

	{item "grenade" "rdg1_smoke" 			999  {value 1}}
)

(define "items_light_fin"

;// pistol
	{item "m1907_mag"				"ammo" 999 {value 1}}

;// smg
	{item "suomi_drum"				"ammo" 999 {value 1}}
	{item "suomi_stick"				"ammo" 999 {value 1}}
	{item "bergmann_stick"			"ammo" 999 {value 1}}

;// rifle
	{item "rifle_swe" "clip"		"ammo" 999 {value 1}}

;// mg
	{item "chauchat"				"ammo" 999 {value 1}}
	{item "kg_m21_mag"				"ammo" 999 {value 1}}
	{item "m26"						"ammo" 999 {value 1}}
	{item "madsen"					"ammo" 999 {value 1}}
	{item "mgun_rus" "l33_36"		"ammo" 999 {value 1}}

;// Light weaponry
	{item "mortarfin_81" "he"		"ammo" 999  {value 1}}
	{item "mortarfin_81" "sm"		"ammo" 999  {value 1}}
	{item "mortarfin_120" "he"		"ammo" 999  {value 1}}

;// Grenade
	{item "grenade" "m32"					999  {value 1}}
	{item "grenade" "m32_stick"				999  {value 1}}
	{item "grenade" "m36"					999  {value 1}}

	{item "grenade" "m32_satchel"			999  {value 1}}
	{item "grenade" "molotov_bundle_fin"	999  {value 1}}
	{item "grenade" "molotov_cocktail_fin"	999  {value 1}}

	{item "grenade" "svkkr_pm"				999  {value 1}}
	{item "grenade" "m42_wp"				999  {value 1}}
	{item "grenade" "m43_smoke"				999  {value 1}}
)

(define "items_light_usa"

;// pistol
	{item "m1911_mag"				"ammo" 999 {value 1}}
	{item "hdm_mag"					"ammo" 999 {value 1}}

;// smg
	{item "thompson_mag" "stick" "20" "ammo" 999 {value 1}}
	{item "m3_grease_mag"			"ammo" 999 {value 1}}
	{item "thompson_mag" "stick" "30" "ammo" 999 {value 1}}
	{item "thompson_mag" "drum"		"ammo" 999 {value 1}}

;// mg
	{item "bar_mag"					"ammo" 999 {value 1}}
	{item "mgun_usa" "belt"			"ammo" 999 {value 1}}
	{item "hmgun_usa"				"ammo" 999 {value 1}}
	{item "hmgun_usa" "api"			"ammo" 999 {value 1}}

;// rifle
	{item "rifle_usa" "clip"		"ammo" 999 {value 1}}
	{item "rifle_usa" "clip" "ap"	"ammo" 999 {value 1}}
	{item "rifle_usa" "clip" "trace" "ammo" 999 {value 1}}
	{item "rifle_usa" "garand_clip" "ammo" 999 {value 1}}
	{item "rifle_usa" "garand_clip" "ap" "ammo" 999 {value 1}}
	{item "rifle_usa" "garand_clip" "trace" "ammo" 999 {value 1}}

	{item "m1_carbine_mag"			"ammo" 999 {value 1}}

;// AT
	{item "usa_grenade"	"he"		"ammo" 999  {value 1}}
	{item "usa_grenade"	"he2"		"ammo" 999  {value 1}}
	{item "usa_grenade"	"heat"		"ammo" 999  {value 1}}
	{item "usa_grenade"	"heata"		"ammo" 999  {value 1}}
	{item "usa_grenade"	"wp"		"ammo" 999  {value 1}}

	{item "bazooka"	"heat"			"ammo" 999  {value 1}}
	{item "bazooka"	"heata"			"ammo" 999  {value 1}}
	{item "bazooka"	"heatb"			"ammo" 999  {value 1}}
	{item "bazooka"	"wp"			"ammo" 999  {value 1}}

	{item "recoilless" "he"			"ammo" 999  {value 1}}
	{item "recoilless" "heat"		"ammo" 999  {value 1}}
	{item "recoilless" "wp"			"ammo" 999  {value 1}}

;// Light weaponry
	{item "mortarusa_60" "he"		"ammo" 999  {value 1}}
	{item "mortarusa_60" "wp"		"ammo" 999  {value 1}}
	{item "mortarusa_81" "he"		"ammo" 999  {value 1}}
	{item "mortarusa_81" "he2"		"ammo" 999  {value 1}}
	{item "mortarusa_81" "sm"		"ammo" 999  {value 1}}
	{item "mortarusa_81" "wp"		"ammo" 999  {value 1}}
	{item "mortarusa_107" "he"		"ammo" 999  {value 1}}
	{item "mortarusa_107" "sm"		"ammo" 999  {value 1}}
	{item "mortarusa_107" "wp"		"ammo" 999  {value 1}}

;// Grenade
	{item "grenade" "mk2" 					999  {value 1}}

	{item "grenade" "m7"					999  {value 1}}

	{item "grenade" "anm8_smoke" 			999  {value 1}}
	{item "grenade" "m15_wp" 				999  {value 1}}
)


(define "items_light_eng"

;// pistol
	{item "7_65mm_pistol"			"ammo" 999 {value 1}}
	{item "eng_revolver_clip_38"	"ammo" 999 {value 1}}
	{item "eng_revolver_clip_45"	"ammo" 999 {value 1}}

;// smg
	{item "sten_mag" "eng_smg"		"ammo" 999 {value 1}}
	{item "lanchester_mag" "eng_smg""ammo" 999 {value 1}}

;// mg
	{item "bren_mag"				"ammo" 999 {value 1}}
	{item "mgun_ger" "belt" "mk2"	"ammo" 999 {value 1}}
	{item "vickers_berthier_mag"	"ammo" 999 {value 1}}
	{item "lewis_mag"				"ammo" 999 {value 1}}
	{item "vickers_go_mag"			"ammo" 999 {value 1}}
	{item "bren_drum_mag"			"ammo" 999 {value 1}}
	{item "mgun_eng" "belt"			"ammo" 999 {value 1}}
	{item "hmgun_eng"				"ammo" 999 {value 1}}

;// rifle
	{item "rifle_eng" "clip"		"ammo" 999 {value 1}}
	{item "de_lisle_carbine_mag" 	"ammo" 999 {value 1}}
	{item "atrifle_eng"	"ap"		"ammo" 999  {value 1}}
	{item "atrifle_eng"	"ap2"		"ammo" 999  {value 1}}

;// AT
	{item "eng_grenade"	"he"		"ammo" 999  {value 1}}
	{item "eng_grenade"	"heat"		"ammo" 999  {value 1}}
	{item "piat_bomb"	"heat"		"ammo" 999  {value 1}}
	{item "piat_bomb"	"heata"		"ammo" 999  {value 1}}

;// Light weaponry
	{item "mortareng_50" "he"		"ammo" 999  {value 1}}
	{item "mortareng_50" "sm"		"ammo" 999  {value 1}}
	{item "mortareng_50" "wp"		"ammo" 999  {value 1}}
	{item "mortareng_81" "he"		"ammo" 999  {value 1}}
	{item "mortareng_81" "sm"		"ammo" 999  {value 1}}
	{item "mortareng_81" "wp"		"ammo" 999  {value 1}}
	{item "mortareng_107" "he"		"ammo" 999  {value 1}}
	{item "mortareng_107" "sm"		"ammo" 999  {value 1}}
	{item "mortareng_107" "wp"		"ammo" 999  {value 1}}

;// Grenade
	{item "grenade" "no36m_early" 			999  {value 1}}
	{item "grenade" "no36m" 				999  {value 1}}
	{item "grenade" "no69" 					999  {value 1}}
	{item "grenade" "no73"					999  {value 1}}
	{item "grenade" "no74"					999  {value 1}}
	{item "grenade" "no75"					999  {value 1}}
	{item "grenade" "no76_ic" 				999  {value 1}}
	{item "grenade" "no82"					999  {value 1}}

	{item "grenade" "no76_ic" 				999  {value 1}}
	{item "grenade" "no8_smoke" 			999  {value 1}}
	{item "grenade" "no77_wp" 				999  {value 1}}
)

(define "items_light_fra"
;// rifle
	{item "rifle_fra" "clip"		"ammo" 999 {value 1}}

;// mg
	{item "fm_24_29_mag"			"ammo" 999 {value 1}}

;// Grenade
	{item "grenade" "mk2" 					999  {value 1}}
)


(define "items_light_generic"
;// flame
	(mod not "mp"
		{item "flame_thrower"			"ammo" 999 {value 1}}
	)
	(mod "mp"
		{item "flame_thrower"			"ammo" 999 {value 1}}
	)

;// pistol
	{item "pistol"					"ammo" 999 {value 1}}

;// other
	{item "bandage_ger"						999 {value 1}}
	{item "bandage_rus"						999 {value 1}}
	{item "bandage_fin"						999 {value 1}}
	{item "bandage_usa"						999 {value 1}}
	{item "bandage_eng"						999 {value 1}}

	{item "knife_ger"						999 {value 1}}
	{item "knife_rus"						999 {value 1}}
	{item "knife_fin"						999 {value 1}}
	{item "knife_usa"						999 {value 1}}
	{item "knife_eng"						999 {value 1}}
)

(define "items_medic"
;// other
	{item "bandage_ger"						999 {value 1}}
	{item "bandage_rus"						999 {value 1}}
	{item "bandage_fin"						999 {value 1}}
	{item "bandage_usa"						999 {value 1}}
	{item "bandage_eng"						999 {value 1}}
)

(define "items_heavy_ger"
	{item "bullet_20_auto"		"aphe"		"ammo" 999 {value 1}}

	{item "bulletger_15_auto"	"ap"		"ammo" 999 {value 1}}
	{item "bulletger_15_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_20_auto"	"ap"		"ammo" 999 {value 1}}
	{item "bulletger_20_auto"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_20_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_30_auto"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_30_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_37_auto"	"ap"		"ammo" 999 {value 1}}
	{item "bulletger_37_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_25"		"ap"		"ammo" 999 {value 1}}

	{item "bulletger_28"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_28"		"he"		"ammo" 999 {value 1}}

	{item "bulletger_37"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletger_37"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_37"		"he"		"ammo" 999 {value 1}}
	{item "bulletger_37"		"heat"		"ammo" 999 {value 1}}

	{item "bullet_37x149" "ger"	"apc"		"ammo" 999 {value 1}}
	{item "bullet_37x149" "ger"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_47"		"apche"		"ammo" 999 {value 1}}
	{item "bulletger_47"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_47"		"he"		"ammo" 999 {value 1}}

	{item "bullet_47x193" "ger"	"apc"		"ammo" 999 {value 1}}
	{item "bullet_47x193" "ger"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_50_l42"	"apche"		"ammo" 999 {value 1}}
	{item "bulletger_50_l42"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_50_l42"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_50_l60"	"apche"		"ammo" 999 {value 1}}
	{item "bulletger_50_l60"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_50_l60"	"he"		"ammo" 999 {value 1}}
	{item "bulletger_50_l60"	"heat"		"ammo" 999 {value 1}}

	{item "bulletger_50_l87"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_50_l87"	"he"		"ammo" 999 {value 1}}

	{item "bullet_75x241" "ger"	"aphe"		"ammo" 999 {value 1}}
	{item "bullet_75x241" "ger"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_75_l24"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_75_l24"	"he"		"ammo" 999 {value 1}}
	{item "bulletger_75_l24"	"heat"		"ammo" 999 {value 1}}
	{item "bulletger_75_l24"	"heata"		"ammo" 999 {value 1}}
	{item "bulletger_75_l24"	"heatb"		"ammo" 999 {value 1}}
	{item "bulletger_75_l24"	"heatc"		"ammo" 999 {value 1}}
	{item "bulletger_75_l24"	"sm"		"ammo" 999 {value 1}}

	{item "bulletger_75_l43"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_75_l43"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_75_l43"	"he"		"ammo" 999 {value 1}}
	{item "bulletger_75_l43"	"heat"		"ammo" 999 {value 1}}
	{item "bulletger_75_l43"	"heatb"		"ammo" 999 {value 1}}
	{item "bulletger_75_l43"	"heatc"		"ammo" 999 {value 1}}

	{item "bulletger_75_l70"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_75_l70"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_75_l70"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_88_l56"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_88_l56"	"apcbche2"	"ammo" 999 {value 1}}
	{item "bulletger_88_l56"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletger_88_l56"	"he"		"ammo" 999 {value 1}}
	{item "bulletger_88_l56"	"heat"		"ammo" 999 {value 1}}

	{item "bulletger_88_l71"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_88_l71"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_105"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletger_105"		"he"		"ammo" 999 {value 1}}
	{item "bulletger_105"		"he2"		"ammo" 999 {value 1}}
	{item "bulletger_105"		"heat"		"ammo" 999 {value 1}}

	{item "bulletger_128"		"apcbche"	"ammo" 999 {value 1}}
	{item "bulletger_128"		"he"		"ammo" 999 {value 1}}

	{item "bulletger_150_l11"	"he"		"ammo" 999 {value 1}}
	{item "bulletger_150_l11"	"he2"		"ammo" 999 {value 1}}

	{item "bulletger_150_l30"	"he"		"ammo" 999 {value 1}}
	{item "bulletger_150_l30"	"heat"		"ammo" 999 {value 1}}

	{item "bullet_155"	"ger"	"he"		"ammo" 999 {value 1}}

	{item "bulletger_170"		"he"		"ammo" 999  {value 1}}

	{item "mortarger_200"		"he"		"ammo" 999  {value 1}}
	{item "mortarger_200"		"sm"		"ammo" 999  {value 1}}

	{item "bulletger_210"		"he"		"ammo" 999 {value 1}}

	{item "150mm_nebelwerfer"				"ammo" 999 {value 1}} ;// 6 rockets costs 180 per salvo
	{item "210mm_nebelwerfer"				"ammo" 999 {value 1}} ;// 5 rockets costs 250 per salvo
	{item "280mm_nebelwerfer"				"ammo" 999 {value 1}} ;// 6 rockets costs 360 per salvo
	{item "300mm_nebelwerfer"				"ammo" 999 {value 1}} ;// 6 rockets costs 360 per salvo
	{item "380mm_rw61"						"ammo" 999 {value 1}}

	{item "bulletger_600"		"he"		"ammo" 999 {value 1}}
	{item "bulletger_600"		"he2"		"ammo" 999 {value 1}}
)

(define "items_heavy_rus"
	{item "bullet_20_auto"		"aphe"		"ammo" 999 {value 1}}

	{item "bulletrus_20_auto"	"ap"		"ammo" 999 {value 1}}
	{item "bulletrus_20_auto"	"apcr"		"ammo" 999 {value 1}}
	{item "bulletrus_20_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletrus_25_auto"	"apbc"		"ammo" 999 {value 1}}
	{item "bulletrus_25_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletrus_37_auto"	"ap"		"ammo" 999 {value 1}}
	{item "bulletrus_37_auto"	"he"		"ammo" 999 {value 1}}

	{item "bulletrus_37"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_37"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_45"		"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_45"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletrus_45"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_57"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_57"		"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_57"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletrus_57"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_76"		"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_76"		"aphebc2"	"ammo" 999 {value 1}}
	{item "bulletrus_76"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletrus_76"		"heat"		"ammo" 999 {value 1}}
	{item "bulletrus_76"		"he"		"ammo" 999 {value 1}}
	
	{item "bulletrus_76_l55"	"apbc"		"ammo" 999 {value 1}}
	{item "bulletrus_76_l55"	"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_76_l55"	"he"		"ammo" 999 {value 1}}

	{item "bulletrus_85"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_85"		"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_85"		"apcr"		"ammo" 999 {value 1}}
	{item "bulletrus_85"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_100"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_100"		"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_100"		"he"		"ammo" 999 {value 1}}

	{item "bullet_107x442" "rus" "apcbche"	"ammo" 999 {value 1}}
	{item "bullet_107x442" "rus" "he"		"ammo" 999 {value 1}}

	{item "bullet_122x159" "rus" "he"		"ammo" 999 {value 1}}
	{item "bullet_122x159" "rus" "wp"		"ammo" 999 {value 1}}

	{item "bulletrus_122_l22"	"he"		"ammo" 999 {value 1}}
	{item "bulletrus_122_l22"	"heat"		"ammo" 999 {value 1}}

	{item "bulletrus_122_l48"	"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_122_l48"	"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_122_l48"	"he"		"ammo" 999 {value 1}}
	{item "bulletrus_122_l48"	"he2"		"ammo" 999 {value 1}}

	{item "bulletrus_125"		"ic"		"ammo" 999 {value 1}}

	{item "bulletrus_130"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_130"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_152"		"aphe"		"ammo" 999 {value 1}}
	{item "bulletrus_152"		"aphebc"	"ammo" 999 {value 1}}
	{item "bulletrus_152"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_152_l24"	"he"		"ammo" 999 {value 1}}

	{item "bulletrus_152_l47"	"he"		"ammo" 999 {value 1}}

	(mod not "mp"
	{item "bulletrus_180"		"he"		"ammo" 999 {value 1}}
	)
	{item "bulletrus_203"		"he"		"ammo" 999 {value 1}}

	{item "bulletrus_280"		"he"		"ammo" 999 {value 1}}

	{item "82mm_rs82"						"ammo" 999 {value 1}}
	{item "82mm_bm8"						"ammo" 999 {value 1}}
	{item "132mm_bm13"						"ammo" 999 {value 1}} ;// 16 rockets costs 400 per salvo
	{item "300mm_bm30"						"ammo" 999 {value 1}} ;// 12 rockets costs 600 per salvo
)

(define "items_heavy_fin"

	{item "mortarfin_170"		"he"		"ammo" 999  {value 1}}

	{item "bulletfin_20"		"ap"		"ammo" 999 {value 1}}
	{item "bulletfin_20_auto"	"ap"		"ammo" 999 {value 1}}
	{item "bulletfin_20_auto"	"he"		"ammo" 999 {value 1}}

	{item "bullet_20x138b_auto" "fin" "ap"	"ammo" 999 {value 1}}
	{item "bullet_20x138b_auto" "fin" "he"	"ammo" 999 {value 1}}

	{item "bullet_40x331_auto" "fin" "apbc"	"ammo" 999 {value 1}}
	{item "bullet_40x331_auto" "fin" "he"	"ammo" 999 {value 1}}

	{item "bullet_37x94" "fin" "aphe"		"ammo" 999 {value 1}}
	{item "bullet_37x94" "fin" "he"			"ammo" 999 {value 1}}
	{item "bullet_37x257" "fin" "ap"		"ammo" 999 {value 1}}
	{item "bullet_37x257" "fin" "he"		"ammo" 999 {value 1}}

	{item "bulletrus_45"		"apcbc"		"ammo" 999 {value 1}}		;// Finnish shell just has to have rus entity name for gun compatibility

	{item "bullet_47x195" "fin" "aphe"		"ammo" 999 {value 1}}
	{item "bullet_47x195" "fin" "he"		"ammo" 999 {value 1}}

	{item "bullet_75x657" "fin" "apbc"		"ammo" 999 {value 1}}
	{item "bullet_75x657" "fin" "he"		"ammo" 999 {value 1}}

	{item "bulletger_75_l43"	"apcbc"		"ammo" 999 {value 1}}		;// Finnish shell just has to have ger entity name for gun compatibility
	{item "bulletrus_76"		"apcbc"		"ammo" 999 {value 1}}		;// Finnish shell just has to have rus entity name for gun compatibility
	{item "bulletrus_76"		"heatb"		"ammo" 999 {value 1}}	;// Finnish shell just has to have rus entity name for gun compatibility
	{item "bulletrus_76"		"heatc"		"ammo" 999 {value 1}}	;// Finnish shell just has to have rus entity name for gun compatibility

	{item "bulletrus_76_l55"	"apcbc"		"ammo" 999 {value 1}}		;// Finnish shell just has to have rus entity name for gun compatibility

	{item "bullet_84x294" "fin" "ap"		"ammo" 999 {value 1}}
	{item "bullet_84x294" "fin" "he"		"ammo" 999 {value 1}}

	{item "bullet_105x380" "fin" "he"		"ammo" 999 {value 1}}
	{item "bullet_105x764" "he"				"ammo" 999 {value 1}}
	{item "bullet_107x442" "fin" "he"		"ammo" 999 {value 1}}

	{item "bullet_114x86" "fin" "he"		"ammo" 999 {value 1}}
	{item "bullet_114x86" "fin" "wp"		"ammo" 999 {value 1}}
	{item "bullet_114x86" "fin" "heat"		"ammo" 999 {value 1}}

	{item "bullet_120_l27" "fin" "he"		"ammo" 999 {value 1}}

	{item "bullet_122x159" "fin" "he"		"ammo" 999 {value 1}}
	{item "bullet_122x159" "fin" "wp"		"ammo" 999 {value 1}}

	{item "bullet_155_l15" "fin" "he"		"ammo" 999 {value 1}}
	{item "bullet_203_l16" "fin" "he"		"ammo" 999 {value 1}}

	{item "mortarfin_300" "he"				"ammo" 999 {value 1}}
)

(define "items_heavy_usa"
	{item "bulletusa_37"		"ap"		"ammo" 999 {value 1}}
	{item "bulletusa_37"		"apcbc"		"ammo" 999 {value 1}}
	{item "bulletusa_37"		"he"		"ammo" 999 {value 1}}

	{item "bulletusa_37_auto"	"apc"		"ammo" 999 {value 1}}
	{item "bulletusa_37_auto"	"he"		"ammo" 999 {value 1}}

	{item "bullet_40x331_auto" "usa" "apbc"	"ammo" 999 {value 1}}
	{item "bullet_40x331_auto" "usa" "he"	"ammo" 999 {value 1}}

	{item "bullet_57x441" "usa" "ap"		"ammo" 999 {value 1}}
	{item "bullet_57x441" "usa" "apcbche"	"ammo" 999 {value 1}}
	{item "bullet_57x441" "usa" "he"		"ammo" 999 {value 1}}

	{item "bulletusa_75x272"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_75x272"	"heat"		"ammo" 999 {value 1}}
	{item "bulletusa_75x272"	"wp"		"ammo" 999 {value 1}}

	{item "bulletusa_75x350"	"ap"		"ammo" 999 {value 1}}
	{item "bulletusa_75x350"	"apcbc"		"ammo" 999 {value 1}}
	{item "bulletusa_75x350"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletusa_75x350"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_75x350"	"wp"		"ammo" 999 {value 1}}

	{item "bulletusa_76x539"	"ap"		"ammo" 999 {value 1}}
	{item "bulletusa_76x539"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletusa_76x539"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_76x539"	"hvap"		"ammo" 999 {value 1}}
	{item "bulletusa_76x539"	"sm"		"ammo" 999 {value 1}}

	{item "bulletusa_76x585"	"ap"		"ammo" 999 {value 1}}
	{item "bulletusa_76x585"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletusa_76x585"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_76x585"	"hvap"		"ammo" 999 {value 1}}
	{item "bulletusa_76x585"	"sm"		"ammo" 999 {value 1}}

	{item "bulletusa_90x600"	"ap"		"ammo" 999 {value 1}}
	{item "bulletusa_90x600"	"apbc"		"ammo" 999 {value 1}}
	{item "bulletusa_90x600"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletusa_90x600"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_90x600"	"hvap"		"ammo" 999 {value 1}}

	{item "bulletusa_90x1270"	"apbc"		"ammo" 999 {value 1}}
	{item "bulletusa_90x1270"	"apcbche"	"ammo" 999 {value 1}}
	{item "bulletusa_90x1270"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_90x1270"	"hvap"		"ammo" 999 {value 1}}

	{item "bulletusa_105"		"he"		"ammo" 999 {value 1}}
	{item "bulletusa_105"		"heat"		"ammo" 999 {value 1}}
	{item "bulletusa_105"		"sm"		"ammo" 999 {value 1}}
	{item "bulletusa_105"		"wp"		"ammo" 999 {value 1}}

	{item "bullet_155" "usa"	"aphebc"	"ammo" 999 {value 1}}
	{item "bullet_155" "usa"	"he"		"ammo" 999 {value 1}}
	{item "bullet_155" "usa"	"he2"		"ammo" 999 {value 1}}
	{item "bullet_155" "usa"	"sm"		"ammo" 999 {value 1}}
	{item "bullet_155" "usa"	"sm2"		"ammo" 999 {value 1}}
	{item "bullet_155" "usa"	"wp"		"ammo" 999 {value 1}}
	{item "bullet_155" "usa"	"wp2"		"ammo" 999 {value 1}}

	{item "bullet_155_l15" "usa" "he"		"ammo" 999 {value 1}}

	{item "bulletusa_155_m1"	"he"		"ammo" 999 {value 1}}
	{item "bulletusa_155_m1"	"sm"		"ammo" 999 {value 1}}
	{item "bulletusa_155_m1"	"wp"		"ammo" 999 {value 1}}

	{item "bulletusa_203"		"he"		"ammo" 999 {value 1}}

	{item "114mm_m8"						"ammo" 999 {value 1}} ;// 60 rockets costs 480 per salvo
	{item "127mm_hvar" "aphe"				"ammo" 999 {value 1}}
	{item "127mm_hvar" "he"					"ammo" 999 {value 1}}
)

(define "items_heavy_eng"
	{item "bulleteng_15_auto"		"ap"	"ammo" 999 {value 1}}

	{item "bulleteng_20_auto" "box"	"ap"	"ammo" 999 {value 1}}
	{item "bulleteng_20_auto" "box"	"he"	"ammo" 999 {value 1}}
	{item "bulleteng_20_auto" "box"	"hei"	"ammo" 999 {value 1}}
	{item "bulleteng_20_auto" "drum" "ap"	"ammo" 999 {value 1}}
	{item "bulleteng_20_auto" "drum" "he"	"ammo" 999 {value 1}}
	{item "bulleteng_20_auto" "drum" "hei"	"ammo" 999 {value 1}}

	{item "bullet_37x257" "eng"		"ap"	"ammo" 999 {value 1}}
	{item "bullet_37x257" "eng"		"he"	"ammo" 999 {value 1}}

	{item "bulleteng_40"		"ap"		"ammo" 999 {value 1}}
	{item "bulleteng_40"		"ap2"		"ammo" 999 {value 1}}
	{item "bulleteng_40"		"apcbc"		"ammo" 999 {value 1}}
	{item "bulleteng_40"		"he"		"ammo" 999 {value 1}}
	{item "bulleteng_40" "littlejohn" "apcr" "ammo" 999 {value 1}}
	{item "bulleteng_40" "littlejohn" "apcr2" "ammo" 999 {value 1}}

	{item "bullet_40x331_auto" "eng" "apbc"	"ammo" 999 {value 1}}
	{item "bullet_40x331_auto" "eng" "sap"	"ammo" 999 {value 1}}
	{item "bullet_40x331_auto" "eng" "he"	"ammo" 999 {value 1}}

	{item "bullet_57x441" "eng"	"ap"		"ammo" 999 {value 1}}
	{item "bullet_57x441" "eng"	"apc"		"ammo" 999 {value 1}}
	{item "bullet_57x441" "eng"	"apcbc"		"ammo" 999 {value 1}}
	{item "bullet_57x441" "eng"	"apcr"		"ammo" 999 {value 1}}
	{item "bullet_57x441" "eng"	"apds"		"ammo" 999 {value 1}}
	{item "bullet_57x441" "eng"	"he"		"ammo" 999 {value 1}}

	{item "bulleteng_76_l25"	"he"		"ammo" 999 {value 1}}
	{item "bulleteng_76_l25"	"sm"		"ammo" 999 {value 1}}

	{item "bulleteng_76"	"ap"			"ammo" 999 {value 1}}
	{item "bulleteng_76"	"apc"			"ammo" 999 {value 1}}
	{item "bulleteng_76"	"apcbc"			"ammo" 999 {value 1}}
	{item "bulleteng_76"	"apds"			"ammo" 999 {value 1}}
	{item "bulleteng_76"	"he"			"ammo" 999 {value 1}}
	{item "bulleteng_76"	"he2"			"ammo" 999 {value 1}}

	{item "bulleteng_77"	"apcbc"			"ammo" 999 {value 1}}
	{item "bulleteng_77"	"apds"			"ammo" 999 {value 1}}
	{item "bulleteng_77"	"he"			"ammo" 999 {value 1}}

	{item "bullet_84x294" "eng" "ap"		"ammo" 999 {value 1}}
	{item "bullet_84x294" "eng" "he"		"ammo" 999 {value 1}}

	{item "bulleteng_88"		"ap"		"ammo" 999 {value 1}}
	{item "bulleteng_88" 		"he"		"ammo" 999 {value 1}}
	{item "bulleteng_88" 		"sm"		"ammo" 999 {value 1}}

	{item "bulleteng_94"		"he"		"ammo" 999 {value 1}}
	{item "bulleteng_94" 		"heat"		"ammo" 999 {value 1}}
	{item "bulleteng_94" 		"wp"		"ammo" 999 {value 1}}

	{item "bulleteng_94_l50"	"ap"		"ammo" 999 {value 1}}
	{item "bulleteng_94_l50" 	"aphe"		"ammo" 999 {value 1}}
	{item "bulleteng_94_l50" 	"he"		"ammo" 999 {value 1}}

	{item "bulleteng_95"		"he"		"ammo" 999 {value 1}}
	{item "bulleteng_95" 		"heat"		"ammo" 999 {value 1}}
	{item "bulleteng_95" 		"sm"		"ammo" 999 {value 1}}

	{item "bullet_114x86" "eng"	"he"		"ammo" 999 {value 1}}
	{item "bullet_114x86" "eng"	"wp"		"ammo" 999 {value 1}}

	{item "bulleteng_114"		"he"		"ammo" 999 {value 1}}

	{item "bulleteng_127"		"he"		"ammo" 999 {value 1}}

	{item "bulleteng_140"		"he"		"ammo" 999 {value 1}}
	{item "bulleteng_140"		"he2"		"ammo" 999 {value 1}}
	{item "bulleteng_140"		"sm"		"ammo" 999 {value 1}}

	{item "bulleteng_152"		"he"		"ammo" 999 {value 1}}
	{item "bulleteng_152"		"he2"		"ammo" 999 {value 1}}

	{item "bulleteng_183"		"he"		"ammo" 999 {value 1}}

	{item "bulleteng_203"		"he"		"ammo" 999 {value 1}}

	{item "bulleteng_230"		"he"		"ammo" 999 {value 1}} ;// AVRE Bomb

	{item "50mm_rocket_grapnel"				"ammo" 999 {value 1}}
	{item "76mm_landmattress"				"ammo" 999 {value 1}} ;// 30 rockets costs 210 per salvo
	{item "76mm_rp3"			"he"		"ammo" 999 {value 1}} ;// 
)

(define "items_heavy_fra"
	{item "bulletfra_25"			"ap"	"ammo" 999 {value 1}}
)

(define "items_heavy_generic"
	{item "sandbag_vehicle"						999 {value 1}}
)

(define "items_engineer"
;// fortification tools
	{item "shovel_ger"							1 {value 1}}
	{item "shovel_rus"							1 {value 1}}
	{item "shovel_fin"							1 {value 1}}
	{item "shovel_usa"							1 {value 1}}
	{item "shovel_eng"							1 {value 1}}
	{item "pickaxe"								1 {value 1}}
	{item "tent_kit"							2 {value 1}}
	{item "sandbag_vehicle"						10 {value 1}}

;// general tools
	{item "mine_detector"						1 {value 1}}
	{item "repair_kit"							999 {value 1}}

;// special ammo
	{item "flame_thrower"				"ammo"  999 {value 1}}
)

(define "items_explosives"
;// explosives
	{item "dynamite_ger_x7"						10 {value 1}}
	{item "geballteladung_3kg"					10 {value 1}}
	{item "satchel_charge_rus"					10 {value 1}}
	{item "satchel_charge_usa"					10 {value 1}}
	{item "satchel_charge_eng"					10 {value 1}}
	{item "tnt_eng"								10 {value 1}}
	{item "compositionb_x4"						10 {value 1}}

;// grenade mine hybrid
	{item "grenade" "m7"						10 {value 1}}
	{item "grenade" "no75"						10 {value 1}}

;// mines
	{item "s" "mine" 							10 {value 1}}
	{item "pmd" "mine" 							10 {value 1}}
	{item "m2" "mine" 							10 {value 1}}
	{item "m6" "mine" 							10 {value 1}}
	{item "luhas" "mine" 						10 {value 1}}
	{item "ap_shrapnel_mk1" "mine" 				10 {value 1}}

	{item "m39" "mine" 							10 {value 1}}
	{item "tm_35" "mine" 						10 {value 1}}
	{item "tm_41" "mine" 						10 {value 1}}
	{item "tmi_35" "mine" 						10 {value 1}}
	{item "tmi_43" "mine" 						10 {value 1}}
	{item "tmd_b" "mine" 						10 {value 1}}
	{item "tmd_44" "mine" 						10 {value 1}}
	{item "m1a1" "mine" 						10 {value 1}}
	{item "at_gs_mk4" "mine" 					10 {value 1}}
	{item "at_gs_mk5" "mine" 					10 {value 1}}
)

;/*=================== Item Defines End ===================*/


;/*=================== Supply Defines Begin ===================*/


(define "supply_medic"
	{extender "supply_zone"
		{resupply
			("items_medic")
		}
		{radius 			5}		;// resupply radius in meter
		{resupplyPeriod 	1}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}		;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "supply_ammo_fixed"			;// Stationary crates in missions
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{radius				8}		;// resupply radius in meter
		{resupplyPeriod		2}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "supply_ammo"				;// Carryable crates and small trailers
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{radius				15}		;// resupply radius in meter
		{resupplyPeriod		2}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit				0}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "flag_ammo"
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_engineer")
			("items_explosives")
		}
		{radius				15}		;// resupply radius in meter
		{resupplyPeriod 	2}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit				0}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "flag_ammo_heavy"
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{radius 			15}		;// resupply radius in meter
		{resupplyPeriod 	2}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "crate_ammo_heavy"
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{radius 			15}		;// resupply radius in meter
		{resupplyPeriod 	2}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "truck_ammo" ;// not used
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{mechanicResources {amount 10}{value 1}}
		{radius				12}		;// resupply radius in meter
		{resupplyPeriod		2}		;// resupply period in seconds
		{regenerationPeriod 0}		;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit				0}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "truck_ammo_heavy"
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{radius 			15}			;// resupply radius in meter
		{resupplyPeriod 	2}			;// resupply period in seconds
		{regenerationPeriod 0}			;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}		;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "truck_ammo_heavy_2x"
	{extender "supply_zone"
		{resupply
			("items_light_generic")
			("items_light_ger")
			("items_light_rus")
			("items_light_eng")
			("items_light_usa")
			("items_light_fin")
			("items_light_fra")
			("items_heavy_generic")
			("items_heavy_ger")
			("items_heavy_rus")
			("items_heavy_eng")
			("items_heavy_fin")
			("items_heavy_usa")
			("items_engineer")
			("items_explosives")
		}
		{radius 			15}			;// resupply radius in meter
		{resupplyPeriod 	2}			;// resupply period in seconds
		{regenerationPeriod 0}			;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}		;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "supply_fuel"					;// Fuel truck. Only re-supplies fuel 
	{extender "supply_zone"
		{fuel 	{amount 1}	{value 1}}
		{resupply
			{item "flame_thrower" "ammo" 999 {value 1}}
		}
		{radius 			15}			;// resupply radius in meter
		{resupplyPeriod 	2}			;// resupply period in seconds
		{regenerationPeriod 2}			;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				99999999}	;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "supply_engineer_light"
	{extender "supply_zone"
		{resupply
			("items_engineer")
			("items_explosives")
		}
		{mechanicResources {amount 10}{value 1}}
		{radius 			15}			;// resupply radius in meter
		{resupplyPeriod 	2}			;// resupply period in seconds
		{regenerationPeriod 0}			;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}		;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "supply_engineer"
	{extender "supply_zone"
		{resupply
			("items_engineer")
			("items_explosives")
		}
		{mechanicResources {amount 10}{value 1}}
		{radius 			15}			;// resupply radius in meter
		{resupplyPeriod 	2}			;// resupply period in seconds
		{regenerationPeriod 0}			;// regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				0}		;// max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.25}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)
